Repository ministero-salute/it-dgc-verificaC19-android, pull requests merged in 2021-06, with the labels that each got.

#20 fix: xml comment fix
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/background_rounded_blue.xml
  app/src/main/res/drawable/background_rounded_white.xml
  app/src/main/res/drawable/circular.xml
  app/src/main/res/font/titiliumfont.xml
  app/src/main/res/layout/activity_first.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_verification.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/styles.xml
Labels: bug

#57 feat: update strings
  app/src/main/res/values/strings.xml
Labels: enhancement

#54 Improve dependencies paragraph
  README.md
Labels: documentation, enhancement
